[workspace]
resolver = "2"
members = ["bindings/local/rust/crates/core", "crates/testkit"]
default-members = ["crates/testkit"]

[workspace.dependencies]
cucumber = "0.20"
flagset = "0.4.5"
futures = "0.3"
proptest = "1.4.0"
serde = "^1.0"
serde_repr = "^0.1"
tokio = { version = "1.10", features = ["macros", "rt-multi-thread", "time"] }
